route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'send_email'
receivers:
  - name: 'send_email'
    email_configs:
     - to: shingneprathamesh5@gmail.com
       from: aethergen36@gmail.com
       smarthost: smtp.gmail.com:587
       auth_username: aethergen36@gmail.com
       auth_password: uzmt aajz hsse iodq
       require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']