version: '3'
services:
  prom:
    image: pratham17/prom:v11
    container_name: proms-1
    networks:
      my_network:
        ipv4_address: 172.18.0.2
    entrypoint: /root/entrypoint.sh
    ports:
      - "9090:9090"  # Map container port 9090 to host port 9090

  graf:
    image: pratham17/graf:v2
    networks:
      my_network:
        ipv4_address: 172.18.0.3
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000

  jenk:
    image: pratham17/jenkins:v5
    ports:
      - "8084:8080"
    container_name: jenk-host
    networks:
      my_network:
        ipv4_address: 172.18.0.4
    entrypoint: /entrypoint.sh

  dock:
    image: pratham17/dock:v3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    networks:
      my_network:
        ipv4_address: 172.18.0.5
    container_name: dock-host
    privileged: true
    entrypoint: /entrypoint.sh


networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24